### ISSUE TITLE
Highlight differences to jschniper/gelf_logger

### ISSUE THREAD

**Issue by chazsconi** [elridion/gelfx#4]
Hi

This looks like a good repo, however I assume you are aware of https://github.com/jschniper/gelf_logger - would you be able to highlight what the differences are and what advantages using this one is?  One immediate benefit I see is that this has TCP support, however would this library suffer from the issues discussed in this PR? https://github.com/jschniper/gelf_logger/pull/27

Thanks a lot

Charles

**Comment by elridion** [comment]
Hi Charles,

the idea of gelfx was to write a complete-ish (TCP, UDP and HTTP) implementation of a gelf backend for elixir - especially without additional dependencies.

The Problem described in the PR you’ve linked is none to be fixed. Elixir‘s logger implementation uses back pressure an starts to discard messages when the threshold is exceeded.
To minimise this effect when using a connection based protocol e.g. TCP/HTTP I’ve implemented a ets store for situations in which the connection is temporarily closed.
This does not solve the issue of to many messages being send which could result in a increasingly long massage queue of the logger. But right now I have not implemented any solution for this that I have in mind.

Cheers
Hans

**Comment by chazsconi** [comment]
OK great - thanks a lot for the information!
